/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
/*
import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei/native'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    mesh_0: THREE.Mesh
  }
  materials: {
    material_0: THREE.MeshBasicMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(require('../../../../assets/3D_Modell/Haus21_3D-Scan.gltf')) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_0.geometry}
        material={materials.material_0}
      />
    </group>
  )
}

useGLTF.preload(require('../../../../assets/3D_Modell/Haus21_3D-Scan.gltf'))*/